// Purchase-tracker browser checks using an isolated HTTP fixture. No wallets or payments.
// PLAYWRIGHT_MODULE=/path/to/playwright node demo/check-ui.mjs
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile, mkdir} from 'node:fs/promises';
import {generateKeyPairSync, sign} from 'node:crypto';
import {createRequire} from 'node:module';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const publicDir=fileURLToPath(new URL('../motto/public/',import.meta.url));
const screenshots=process.env.UI_SCREENSHOT_DIR||join(tmpdir(),'motto-ui-check');
await mkdir(screenshots,{recursive:true});
const {privateKey,publicKey}=generateKeyPairSync('ed25519');
const devicePublicKey=publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('hex');
const terms={network:'devnet',console_purchase:false,devicePublicKey,items:{}};
let records=[], recordsPrivate=false, writes=0;const streams=new Set();
const makeHold=(status,extra={})=>({id:'fixture-purchase',item:'design_assets',title:'Design asset pack',status,hold_usd:'1.00',check_fee_usd:'0.00',network:'devnet',startedAt:Date.now(),...extra});
const server=createServer(async(req,res)=>{
 const path=new URL(req.url,'http://localhost').pathname;
 const json=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};
 if(path==='/v1/terms')return json(terms);
 if(recordsPrivate&&(path==='/v1/holds'||path==='/v1/events'))return json({error:'private_records_require_local_or_admin_access'},401);
 if(path==='/v1/holds')return json({holds:records});
 if(path.startsWith('/v1/holds/'))return json(records.find(h=>h.id===decodeURIComponent(path.split('/').at(-1)))??{});
 if(path==='/v1/events'){res.writeHead(200,{'Content-Type':'text/event-stream'});res.write(': connected\n\n');streams.add(res);req.on('close',()=>streams.delete(res));return;}
 if(req.method!=='GET'){writes++;return json({error:'Read-only tracker'},405);}
 const file=resolve(publicDir,path==='/'?'index.html':'.'+path);
 if(!file.startsWith(publicDir))return json({},404);
 try{const data=await readFile(file);res.writeHead(200,{'Content-Type':file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':file.endsWith('.woff2')?'font/woff2':'text/html'});res.end(data);}catch{json({},404);}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
let browser;
try{
 browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}), errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const text=selector=>page.locator(selector).innerText();
 const load=async list=>{records=list;await page.goto(base);await page.waitForFunction(()=>document.querySelector('#network').textContent.includes('DEVNET'));};
 await load([{id:'legacy-demo',item:'research',query:'Do not show this old topic',status:'kept',startedAt:1}]);
 assert.equal(await page.locator('#request-form').count(),0);
 assert.equal(await page.locator('.beta').count(),0);
 assert.equal(await text('#run-count'),'0');
 assert.equal(await text('#ceiling'),'—');
 assert.equal(await page.locator('#open-receipt').isDisabled(),true);
 assert.doesNotMatch(await text('body'),/research|topic|virtual|beta|Do not show this old topic/i);
 await page.screenshot({path:join(screenshots,'desktop-empty.png'),fullPage:true});
 console.log('PASS purchase tracker removes beta, virtual and research UI, hides legacy demo records, and has no checkout');
 await load([makeHold('fetching')]);
 assert.equal(await text('#charged'),'—');assert.equal(await text('#returned'),'—');
 assert.equal(await page.locator('[data-step="1"]').getAttribute('aria-current'),'step');
 await page.waitForFunction(()=>document.body.dataset.stream==='live');
 assert.match(await text('#progress-detail'),/preparing your result/);
 assert.equal(await page.locator('.step.active i').evaluate(el=>getComputedStyle(el,'::before').animationName),'working-ring');
 assert.equal(await page.locator('#delivery-panel').getAttribute('aria-busy'),'true');
 for(const stream of streams)stream.end();
 await page.waitForFunction(()=>document.body.dataset.stream==='offline');
 assert.match(await text('#progress-detail'),/disconnected/);
 assert.equal(await page.locator('.step.active i').evaluate(el=>getComputedStyle(el,'::before').animationPlayState),'paused');
 await page.waitForFunction(()=>document.body.dataset.stream==='live');
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('.step.active i').evaluate(el=>getComputedStyle(el,'::before').animationName),'none');
 assert.equal(await page.locator('#delivery-panel').evaluate(el=>getComputedStyle(el,'::before').animationName),'none');
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.evaluate(()=>{window.moneyAnimations=0;document.querySelector('.money-card').addEventListener('animationstart',e=>{if(e.animationName==='money-highlight')window.moneyAnimations++;});});
 console.log('PASS observed-step pulse, disconnection pause, explanatory status and reduced motion');
 const payload={holdId:'fixture-purchase',item:'design_assets',outcome:'inconclusive',reason:'The provider result was incomplete. The authorization was returned.',ts:Date.now()};
 const reading={...payload,signature:sign(null,Buffer.from(JSON.stringify(payload)),privateKey).toString('hex'),devicePublicKey};
 const settled=makeHold('refunded',{outcome:'inconclusive',charged_usd:'0.00',returned_usd:'1.00',reading});
 records=[settled];for(const stream of streams)stream.write(`data: ${JSON.stringify(settled)}\n\n`);
 await page.waitForFunction(()=>document.querySelector('#returned').textContent==='$1.00');
 await page.waitForFunction(()=>window.moneyAnimations===1);
 assert.equal(await page.locator('#delivery-panel').getAttribute('aria-busy'),'false');
 assert.equal(await page.locator('.step.active').count(),0);
 for(const stream of streams)stream.write(`data: ${JSON.stringify(settled)}\n\n`);
 await page.waitForTimeout(150);
 assert.equal(await page.evaluate(()=>window.moneyAnimations),1);
 console.log('PASS settled amounts highlight once, duplicate updates do not replay, completed steps stop pulsing');
 await page.click('#open-receipt');await page.click('#verify');
 await page.waitForFunction(()=>document.querySelector('#signature-state').textContent.startsWith('Verified'));
 await page.getByLabel('Close receipt',{exact:true}).click();
 const downloaded=page.waitForEvent('download');await page.click('#download-receipt');assert.match((await downloaded).suggestedFilename(),/fixture-purchase/);
 await page.locator('h1').click();await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:join(screenshots,'desktop-returned.png'),fullPage:true});
 console.log('PASS live hold-to-return transition, exact ledger amounts, signature verification and receipt download');
 await load([makeHold('settle_failed',{outcome:'delivered',charged_usd:null,returned_usd:null})]);
 assert.equal(await text('#charged'),'—');assert.equal(await text('#returned'),'—');assert.match(await text('#progress-count'),/Needs attention/);
 assert.equal(await page.locator('#run-status').getAttribute('data-state'),'attention');
 await load([makeHold('refunded',{outcome:'check_failed',charged_usd:'0.00',returned_usd:'1.00'})]);
 assert.match(await page.locator('[data-step="2"]').getAttribute('class'),/failed/);
 assert.match(await page.locator('[data-step="3"]').getAttribute('class'),/done/);
 console.log('PASS unconfirmed settlement and failed evidence stay distinct from successful payment');
 await load([makeHold('kept',{id:'fixture-delivered',charged_usd:'1.00',returned_usd:'0.00',outcome:'delivered',reading:{reason:'The purchased files were delivered.'}})]);
 assert.equal(await text('#purchase-query'),'Design asset pack');
 assert.match(await text('#purchase-contract'),/files were delivered/);
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const money=await page.locator('.money-card').boundingBox(), journey=await page.locator('.journey').boundingBox();assert.ok(money.y<journey.y);
 await page.screenshot({path:join(screenshots,'mobile-delivered.png'),fullPage:true});
 await page.setViewportSize({width:320,height:740});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 console.log('PASS delivered evidence and mobile layout at 390px and 320px');
 recordsPrivate=true;terms.console_purchase=false;await load([]);
 await page.waitForFunction(()=>document.querySelector('#connection').textContent.includes('private activity'));
 assert.match(await text('#progress-detail'),/activity is private/);assert.equal(await page.locator('.step.active').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS private activity explains access instead of showing an endless reconnect');
 assert.equal(writes,0);assert.deepEqual(errors,[]);
 console.log(`All browser checks passed. Screenshots: ${screenshots}`);
}finally{
 await browser?.close();for(const stream of streams)stream.end();await new Promise(resolve=>server.close(resolve));
}
